### ISSUE TITLE
how to get feedback from devices?

### ISSUE THREAD

**Issue by pyxiscloud** [xuebing1110/migateway#2]
Hello,
I've write code to control Aqara and it works.
But how can I get feedback from device?

```golang
func main() {
    manager, err := migateway.NewAqaraManager(nil)
    if err != nil {
        println("connection error", err)
    } else {
        manager.SetAESKey("B6EC4F2E5D494BE6")
        manager.Plugs["158d00011167f4"].TurnOn()
        time.Sleep(500 * time.Millisecond)
        manager.Plugs["158d00011167f4"].TurnOff()
        time.Sleep(500 * time.Millisecond)
    }
}
```

**Comment by pkgplus** [comment]
You can read `manager.Plugs["158d00011167f4"].IsOn`, the attribute of device will be changed automatically when gateway receive the feedback.
  The report message of device will be send to channel `AqaraManager.GateWay.devMsgs`,and the message consumed when calling `NewAqaraManager`. You can modify the source code to copy message from `devMsgs` channel in function `NewAqaraManager`, and then read it.

**Comment by pyxiscloud** [comment]
Does function RefreshStatus and NewReadRequest works?
they return same values all the time.
I'm try to make read status request and get feedback )
thank you
